### ISSUE TITLE
[Report] [4.0] Unable to download the required update.

### ISSUE THREAD

**Issue by ghost** [holoiso-eol/holoiso#689]
## Your Issue:
```
I installed HoloISO and rebooted into it. I select language, timezone and network interface then there is a error came up, it says "Unable to download the required update. Please check your network connection and try again.". I tried even with VPN.
The error shows for a very short time, i couldn't even read it, i recorded a video and took screenshots from it. It goes to shutdown after the error. This was a loop for me.
```

## Your device's full specs
```
CPU: AMD Ryzen 3 4300GE with Radeon Graphics
GPU: AMD ATI 08:00.0 Renoir
Graphics:
  Device-1: AMD Renoir driver: amdgpu v: kernel
  Display: x11 server: X.org v: 1.21.1.6 with: Xwayland v: 22.1.7 driver:
    X: loaded: amdgpu unloaded: modesetting gpu: amdgpu
    resolution: 1366x768~60Hz
  OpenGL: renderer: AMD Radeon Graphics (renoir LLVM 15.0.6 DRM 3.49
  6.1.5-x86_64-xanmod1)
    v: 4.6 Mesa 22.2.5
```

## Your OS version (`cat /etc/os-release | grep VARIANT_ID | cut -d '"' -f 2`):
```
snapshot20221211.1426
```

## Your installation type:
```
Ventoy
```

## Have you updated your installation recently?
```
nawww
```
![2](https://user-images.githubusercontent.com/61632416/212541420-3a482097-b5c5-4ec7-9cd7-1101cc34acc5.jpeg)
![1](https://user-images.githubusercontent.com/61632416/212541422-392a0c76-4201-4c81-bce9-3023b58ab6f0.jpeg)
